### ISSUE TITLE
Chatting with PDFs not functioning on Firefox-based browsers

### ISSUE THREAD

**Issue by n4ze3m** [n4ze3m/page-assist#228]
pdfjs-dist works fine on Chromium-based browsers, but causes freezing on Firefox. This is a critical bug.

**Comment by zono50** [comment]
Any ETA on when we may expect a fix for this?

**Comment by n4ze3m** [comment]
the Sunday or Monday issue has been fixed :)

**Comment by n4ze3m** [comment]
Hey @zono50, a fix has been released. Let me know if it's working for you.

**Comment by zono50** [comment]
it's still not reading off the page properly 
![image](https://github.com/user-attachments/assets/123b4e8b-41ea-4d26-8420-f8ddfa9968bd)
Am i doing something wrong? i have chat with current page checked

**Comment by n4ze3m** [comment]
Can you check if these settings are enabled? They will perform RAG, but the quality is currently not good as I'm trying to improve it. :)

![image](https://github.com/user-attachments/assets/03e894a8-e84b-421f-9f76-253cad6dd6e2)

**Comment by zono50** [comment]
Yeah that's enabled

**Comment by n4ze3m** [comment]
Current rag quality is bad. I'm trying to fix it and hope to update it this weekend. I closed this issue since the PDF wasn't working on Firefox-based browsers, but that's now fixed. I'll let you know once it's resolved. :)

**Comment by zono50** [comment]
Appreciate you
