### ISSUE TITLE
Why this Extension very lagging

### ISSUE THREAD

**Issue by nth-zik** [n4ze3m/page-assist#303]
I'm using with llava and the extension seem very laggy. Just upload several image and the extension seem freeze, need reload.

**Comment by n4ze3m** [comment]
Hey, sorry for the inconvenience. One of the causes of the lag has been fixed, but there are still a few issues caused by extension storage, as Page Assist doesn't have a backend to store chat histories. We'll work on improving this in future versions.

By the way, which browser are you using: Firefox or Chrome?

**Comment by nth-zik** [comment]
I'm using both Firefox and Chrome, the performance still the same

**Comment by nth-zik** [comment]
It happen after I choose an image, wait 3 - 5s to click send, it freeze my browser too. 
When i use temporary chat, it will better but still laggy than other UI application.

**Comment by amonpaike** [comment]
@n4ze3m Hi. I'm not sure, but I noticed strong slowdowns when the accumulated data became high.
From 50mb and up (when I then exported all the data and then did a reset)
Once it had become very slow even to write simple prompts..  
my export data was about 400mb..

**Comment by n4ze3m** [comment]
Yes, I am aware of this issue. 😞 It is one of the reasons for the lag.

One solution is to set a hard limit on storage in the settings. When the storage becomes full, old chats will be removed automatically. Everything will be configurable.

Another solution is to connect to the Page Assist storage API (which I need to create) to save chat history. However, this would also be optional and configurable through the settings.

Let me see if I can find any other solutions. :)

**Comment by marcelol** [comment]
Any updates?
